name: emo_diary_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  group_button: ^5.3.4
  group_radio_button: ^1.3.0
  expandable_text: ^2.3.0
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.2
  http: ^1.2.2
  firebase_core: ^3.10.0
  cloud_firestore: ^5.5.0
  firebase_database: ^11.3.0
  intl: ^0.20.1
  back_button_interceptor: ^8.0.3
  firebase_messaging: ^15.2.0
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^18.0.1
  win32: ^5.4.0
  firebase_analytics: ^11.4.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

